-- Run this once in the Supabase SQL Editor.
-- This schema is designed for the direct PostgreSQL (pg) version of the app.

CREATE TABLE IF NOT EXISTS public.prayers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    request TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'public'
        CHECK (visibility IN ('public', 'private')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.participants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    session_token TEXT NOT NULL UNIQUE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prayer_id BIGINT NOT NULL UNIQUE
        REFERENCES public.prayers(id) ON DELETE CASCADE,
    participant_id UUID NOT NULL
        REFERENCES public.participants(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.prayer_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prayer_id BIGINT NOT NULL
        REFERENCES public.prayers(id) ON DELETE CASCADE,
    participant_id UUID
        REFERENCES public.participants(id) ON DELETE SET NULL,
    reactor_token TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (prayer_id, reactor_token)
);

CREATE INDEX IF NOT EXISTS idx_prayers_created_at
    ON public.prayers(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_prayers_visibility
    ON public.prayers(visibility);

CREATE INDEX IF NOT EXISTS idx_assignments_participant
    ON public.assignments(participant_id);

CREATE INDEX IF NOT EXISTS idx_assignments_prayer
    ON public.assignments(prayer_id);

CREATE INDEX IF NOT EXISTS idx_reactions_prayer
    ON public.prayer_reactions(prayer_id);

CREATE INDEX IF NOT EXISTS idx_participants_last_seen
    ON public.participants(last_seen);
